spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lib_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lixiaoxin
    password: l3004007788xx
  redis:
    host: localhost
    port: 6379
    password: l3004007788xx
    database: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
